# Generated by Django 3.2.13 on 2023-04-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230406_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='subcat',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='_products_productcategory_parent_+', to='products.ProductCategory'),
        ),
    ]
