# Generated by Django 3.2.13 on 2023-04-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230406_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='subcat',
            new_name='parent',
        ),
    ]
